version: "3.9"

services:
    mysql:
        image: mysql:8.0
        container_name: petzone_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}" ]
            interval: 5s
            timeout: 5s
            retries: 10

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: petzone_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - vendor:/var/www/vendor
            - ./storage:/var/www/storage
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel

    webserver:
        image: nginx:1.25-alpine
        container_name: petzone_webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./_docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            app:
                condition: service_started
        networks:
            - laravel

    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            webserver:
                condition: service_started
        command: certonly --webroot --webroot-path=/var/www/public --email markevychdmytro05@gmail.com --agree-tos --no-eff-email -d petzone.pp.ua -d www.petzone.pp.ua
        volumes:
            - ./etc/letsencrypt:/etc/letsencrypt
            - .:/var/www
        networks:
            - laravel

volumes:
    dbdata:
    vendor:
    storage:
    etc-letsencrypt:

networks:
    laravel:
        driver: bridge
