version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - vendor:/var/www/vendor
            - storage:/var/www/storage
        depends_on:
            - mysql
        networks:
            - laravel

    webserver:
        image: nginx:1.25-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - etc-letsencrypt:/etc/letsencrypt
        depends_on:
            - app
        networks:
            - laravel

    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            - webserver
        command: certonly --webroot --webroot-path=/var/www/public --email markevychdmytro05@example.com --agree-tos --no-eff-email -d petzone.pp.ua -d www.petzone.pp.ua
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
            - .:/var/www
        networks:
            - laravel

volumes:
    dbdata:
    vendor:
    storage:
    etc-letsencrypt:

networks:
    laravel:
        driver: bridge
