name: PetZone deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            cd ${{ vars.PROJECT_PATH }}

            git fetch origin main
            git reset --hard origin/main

            docker compose run --rm app composer install --no-dev --optimize-autoloader

            docker compose run --rm app npm ci
            docker compose run --rm app npm run build

            docker compose run --rm app php artisan optimize:clear

            docker compose down
            docker compose up -d --build

            docker compose exec -T app php artisan migrate --force
